name: Nightly FINS Spawning Data Download

on:
  schedule:
    - cron: '30 3 * * *'  # 3:30 AM UTC = 8:30 PM PT (outside maintenance window)
  workflow_dispatch:      # Optional: allows manual run via GitHub

jobs:
  download:
    runs-on: ubuntu-latest
    
    env:
      FINS_API_KEY: ${{ secrets.FINS_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            httr
            jsonlite
            lubridate
            readr
            dplyr

      - name: Run download script
        run: Rscript R/nightly_fins_spawning_download.R
      
      - name: Commit new data file
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          if [[ -f data/SpawningData.csv ]]; then
            git add data/SpawningData.csv
            git add logs/fins_spawning_download.log
            git commit -m "Update latest FINS data - $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
		git pull
            git push
          else
            echo "No data file found, skipping commit"
          fi